CREATE TABLE IF NOT EXISTS USER_ECOMMERCE (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255) UNIQUE,
    PHONE varchar(255) UNIQUE,
    BALANCE varchar(255),
    ROLE varchar(4),
    PRIMARY KEY (USER_ID)
);
CREATE TABLE IF NOT EXISTS PRODUCT_ECOMMERCE(
    ASIN INT NOT NULL AUTO_INCREMENT,
    NAME varchar(255),
    PRICE DECIMAL,
    QUANTITY INT,
    PRIMARY KEY (ASIN)
);
CREATE TABLE IF NOT EXISTS ORDER_ECOMMERCE(
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_TOTAL DECIMAL,
    ORDER_STATUS varchar(8),
    ORDER_PAYMENT varchar (10),
    DONE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    RECEIVED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ORDER_ID)
);
